apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testappv1-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp2
  project: test
  source:
    repoURL: https://github.com/jrg-sierra/testappv1.git
    targetRevision: HEAD
    path: dev
  
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true 